// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WorkFit.CodeReview.Infrastructure.Data;

#nullable disable

namespace WorkFit.CodeReview.Infrastructure.Migrations
{
    [DbContext(typeof(CodeReviewDbContext))]
    [Migration("20260810000000_AddEmployeeIdToCodeReviewLog")]
    partial class AddEmployeeIdToCodeReviewLog
    {
    }
}
