// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WorkFit.ProjectManagement.Infrastructure;

#nullable disable

namespace WorkFit.ProjectManagement.Infrastructure.Migrations
{
    [DbContext(typeof(WorkFitProjectDbContext))]
    [Migration("20260810123000_AddGitHubBranchNodeIdToTask")]
    partial class AddGitHubBranchNodeIdToTask
    {
    }
}
