<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Assessment Module\WorkFit.Assessments.Contracts\WorkFit.Assessments.Contracts.csproj" />
    <ProjectReference Include="..\..\Code Review Module\WorkFit.CodeReview.Contracts\WorkFit.CodeReview.Contracts.csproj" />
    <ProjectReference Include="..\..\Document Module\WorkFit.Documents.Contracts\WorkFit.Documents.Contracts.csproj" />
    <ProjectReference Include="..\..\Email Module\WorkFit.Email.Contracts\WorkFit.Email.Contracts.csproj" />
    <ProjectReference Include="..\..\Engine Module\WorkFit.Engine.Contracts\WorkFit.Engine.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity Module\WorkFit.Identity.Contracts\WorkFit.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\Organization Module\WorkFit.Organizations.Contracts\WorkFit.Organizations.Contracts.csproj" />
    <ProjectReference Include="..\..\Project_Management Module\WorkFit.ProjectManagement.Contracts\WorkFit.ProjectManagement.Contracts.csproj" />
    <ProjectReference Include="..\..\RAG Module\WorkFit.Rag.Contracts\WorkFit.Rag.Contracts.csproj" />
    <ProjectReference Include="..\..\Recommendation Module\WorkFit.Recommendations.Contracts\WorkFit.Recommendations.Contracts.csproj" />
    <ProjectReference Include="..\..\Skills_Taxonomy_Module\WorkFit.Skills.Contracts\WorkFit.Skills.Contracts.csproj" />
    <ProjectReference Include="..\..\Talent_Management Module\WorkFit.TalentManagement.Contracts\WorkFit.TalentManagement.Contracts.csproj" />
    <ProjectReference Include="..\..\WorkFit_Integration Module\WorkFit.Integration.Contracts\WorkFit.Integration.Contracts.csproj" />
    <ProjectReference Include="..\..\WorkFit.SharedKernel\WorkFit.SharedKernel.csproj" />
  </ItemGroup>

</Project>
