// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WorkFit.TalentManagement.Infrastructure.Data;

#nullable disable

namespace WorkFit.TalentManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TalentDbContext))]
    [Migration("20260812011000_AddTaskAllocations")]
    partial class AddTaskAllocations
    {
    }
}
